<template>
    <div class="wrapper relative">
        <!-- <img class="w-full absolute top-0 left-0" src="/icons/purplebg.svg" alt="">
        <img class="w-full absolute top-0 right-0" src="/icons/bluebg.svg" alt="">
        <img class="w-full absolute top-10 right-0" src="/icons/whitebg.svg" alt=""> -->

        <!-- <div class="flex items-center justify-center">
            <img class="lg:-mt-16 sm:-mt-12 -mt-6 lg:w-[100px] sm:w-[80px] w-[50px]" src="/icons/curlybg_one.svg" alt="">
        </div> -->

      <div class="d-container sm:pt-[95px] pt-[30px] sm:pb-[115px] pb-[50px]">
          <div class="flex sm:flex-row flex-col sm:space-y-0 space-y-6 sm:space-x-[100px] lg:space-x-[40x] space-x-0 koro">
              <div class="lg:max-w-[400px] sm:max-w-[300px] sm:max-w-[90%]">
                  <h1 class="text-[#3B57F4] sm:text-[32px] text-[20px] font-bold pb-3">If Your Customers are not using AI, Well, They&apos;re Not Using AI</h1>
                  <p class="sm:text-[16px] text-[14px] pb-3">Agencies & freelancers who are not using AI are going to lose business to the ones that are.</p>
                  <p class="sm:text-[16px] text-[14px] pb-3">AI is fast, quick, & produces better results, which is exactly what businesses want.</p>
                  <p class="sm:text-[16px] text-[14px] pb-3">As we move towards a more digitized world, businesses are going to demand content & assets generated at the click of a button.</p>
                  <p class="sm:text-[16px] text-[14px] pb-3">And those who can't provide it will find it hard to keep up with the competition.</p>
              </div>
              <div class="sm:max-w-[420px] max-w-[100%] w-full relative">
                <img class="w-full" src="/icons/customer_illu1.svg" alt="illustration">
              </div>
          </div>

  
          <div class="text-wrapper lg:p-[80px] sm:p-[40px] p-[20px] sm:mt-[140px] mt-[80px]">
              <h1 class="sm:pt-[40px] pt-[0px] lg:text-[38px] sm:text-[28px] text-[18px] font-bold text-center">...But Starting An Agency That Uses <br class="sm:block hidden"> 
                <span class="bg-gradient-to-r from-[#AB3ADD] to-[#3B57F4] text-transparent bg-clip-text">Artificial Intelligence</span> 
                Requires A Lot Of <br class="sm:block hidden"> Time, Money & Other Resources…
              </h1>
              <h3 class="text-center lg:pb-[120px] sm:pb-[80px] pb-[40px]  pt-[30px]">(Until Now YOU Needed… )</h3>

              <div class="text-wrapper grid lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 sm:gap-x-[60px] gap-x-[10px] sm:gap-y-[80px] gap-y-[40px]">
                <div v-for="(text, i) in textContent" :key="i" class="mx-w-[300px] w-full text-center">
                    <img class="sm:w-[100px] w-[50px] mx-auto" :src=text.icon alt="icon">
                    <h1 class="sm:text-[20px] text-[16px] sm:pt-[30px] pt-[10px] pb-2 font-bold">{{ text.header }}</h1>
                    <p class="sm:text-[16px] text-[14px]">{{ text.desc }}</p>
                    <p class="sm:text-[16px] text-[14px] mt-[20px]">{{ text.cost }}</p>
                </div>
            </div>
         </div>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  const textContent = ref([
      {header:'AI Agency Consultant', desc:'Who knows about AI tools & platforms… and can help you set up an AI Agency', cost:'Cost: $2,500 - $5,000/ Month', icon:'/icons/customer_icon1.svg'},
      {header:'AI Job Finder', desc:'Who scans & filters jobs/gigs for you that can be rendered using AI', cost:'Cost: $2,500 - $5,000/ Month', icon:"/icons/customer_icon2.svg"},
      {header:'AI Tools', desc:'That can generate high-quality content quickly & efficiently.', cost:'', icon:"/icons/customer_icon3.svg" },
      {header:'Copywriters', desc:'To edit & refine the content generated by your AI tools so that it resonates with your target audience.', cost:'', icon:"/icons/customer_icon4.svg"},
      {header:'Machine Learning Experts', desc:'To develop algorithms & train your AI systems to generate content that meets YOUR specific needs.', cost:'', icon:"/icons/customer_icon5.svg"},
      {header:'Digital Marketing Experts', desc:'To develop effective marketing strategies, design engaging campaigns, & optimize your content for search engines & social media.', cost:'', icon:"/icons/customer_icon6.svg"},
      {header:'Analytic Tools', desc:'To track key metrics like engagement rates, click-through rates, & conversion rates.', cost:'', icon:"/icons/customer_icon7.svg"},
      {header:'Project Management Tools', desc:'To manage, collaborate & stay organized.', cost:'', icon:"/icons/customer_icon8.svg"},
      {header:'Business Development Experts', desc:'To grow your agency, identify new opportunities, develop relationships with clients, & close deals.', cost:'', icon:"/icons/customer_icon9.svg"},
  ])

</script>
  
  <style scoped>
  .wrapper{ background: #FAF0FF;}
  .text-wrapper {
    border-radius: 24px;
    background: #FFF;
    /* box-shadow: 0px 61px 80px 0px rgba(59, 87, 244, 0.10); */
  }
  
  
  </style>